### ISSUE TITLE
trajGRU的配置问题

### ISSUE THREAD

**Issue by chaiwentao** [Hzzone/Precipitation-Nowcasting#1]
你好师兄，请问你使用的是pretrained里面的模型吗？我想要装入自己的数据集，并且训练模型，然后输入测试的图片。请问这个具体怎么操作，麻烦了。如果方便，加我QQ：446822646

**Comment by Hzzone** [comment]
这是我自己训练的模型，加载数据直接看HKOIterator。这个要你自己看代码了。

**Comment by chaiwentao** [comment]
谢谢你，我回去自己再研究下。
能否交个朋友啊，我也在成都读研究生，不然你加我qq吧：446822646


 
---原始邮件---
发件人: "Hzzone"<notifications@github.com>
发送时间: 2019年5月11日(星期六) 下午4:38
收件人: "Hzzone/Precipitation-Nowcasting"<Precipitation-Nowcasting@noreply.github.com>;
抄送: "chaiwentao"<446822646@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Hzzone/Precipitation-Nowcasting] trajGRU的配置问题 (#1)



这是我自己训练的模型，加载数据直接看HKOIterator。这个要你自己看代码了。
