### ISSUE TITLE
format of hko dataset

### ISSUE THREAD

**Issue by Melika-Ayoughi** [Hzzone/Precipitation-Nowcasting#5]
hey! first of all thanks for your implementation. what is the format of the hko dataset? I need to use your implementation for my data (sequence of images but in 11 channels) and want to predict the next sequence of frames. Is it possible with this implementation?

**Comment by Hzzone** [comment]
You should implement your own dataloader like [nowcasting/hko/dataloader.py#L183](https://github.com/Hzzone/Precipitation-Nowcasting/blob/b29879896f6cee372f1a16528989fe2d6042bd24/nowcasting/hko/dataloader.py#L183).
