### ISSUE TITLE
input of forecaster

### ISSUE THREAD

**Issue by Melika-Ayoughi** [Hzzone/Precipitation-Nowcasting#6]
As each RNN block receives 2 inputs x and h(history), for the first RNN block of "decoder" (by first I mean the one shown in the image) 1. what do u input instead of history and x? 2. Is it correct to assume input=zeros and history=last output of encoder?

**Comment by Hzzone** [comment]
https://github.com/sxjscience/HKO-7/issues/3#issuecomment-377973660
