### ISSUE TITLE
The reason of applying patch size to moving mnist dataset? 

### ISSUE THREAD

**Issue by jhhuang96** [Hzzone/Precipitation-Nowcasting#7]
When I read Shi's paper "Convolutional LSTM Network: A Machine Learning:Approach for Precipitation Nowcasting", in his experiments on moving mnist dataset, he shape img data (64\*64\*1) to (16\*16\*16).  I'm confused about it, is it because of gpu memory and is it appropriate of this way? Thanks!

**Comment by alexanderhucheerful** [comment]
大佬你好，请问你试过单机多卡训练吗，我使用nn.DataParallel多gpu训练你的模型，但只显示一张卡使用，请问你遇到过这个问题吗，谢谢
